title: Sanjukktha Senthil Kumar
description: Personal site and portfolio
# use the official GitHub Pages Slate theme
theme: jekyll-theme-minimal

# user sites should keep baseurl empty
baseurl: ""
# optional: keeps markdown tidy
markdown: kramdown
